cache: bundler
language: ruby
rvm:
  - 1.9.3
before_install:
  - rm .rvmrc
script:
  - "bundle exec rspec spec/"
sudo: false
addons:
  code_climate:
    repo_token: 3e779acb537014cbfd1a7c48c7a509d3197afe962cd1738e832a46b439919e24
